sudo: false
language: scala
sbt_args: ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M
scala:
  # latest milestone version of the pre-release Scala version
  - 2.12.0-M2
  # current Scala version
  - 2.11.7
matrix:
  fast_finish: true
  allow_failures:
    # we only care if the build against the current Scala version failed
    - scala: 2.12.0-M3
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - tmp/
script:
  - sbt compile
  - sbt clean coverage test
  - sbt bench:test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
